export interface PortfolioSlide {
  type: "image" | "video";
  src: string;
  alt: string;
  title: string;
  description: string;
  year: string;
  height?: number;
  width?: number;
}

export const portfolioMedia: PortfolioSlide[] = [
  {
    type: "image",
    src: "/reproduction-interdite.jpg",
    alt: "Window display in gallery with ceramic vases, beaded keys and carved wood & papier mache sculptures",
    title: "REPRODUCTION INTERDITE",
    description: "Solo show at Gham & Dafe, Montreal QC",
    year: "2025",
    width: 1458,
    height: 1000,
  },
  {
    type: "video",
    src: "/spinoff.mov",
    alt: "Video of a spinning mobile made of wire, papier mache and dangling lucite sculptures",
    title: "SPINOFF",
    description: "Wire, papier mache, lucite, nylon thread",
    year: "2025",
  },
  {
    type: "image",
    src: "/spin-off.jpg",
    alt: "Image of a spinning mobile made of wire, papier mache and dangling lucite sculptures",
    title: "SPINOFF",
    description: "Wire, papier mache, lucite, nylon thread",
    year: "2025",
    height: 1000,
    width: 798,
  },
  {
    type: "image",
    src: "/portal-lamp-cropped.jpg",
    alt: "Multicolored 6-foot tall paper mache lamp and palm tree",
    title: "PORTAL LAMP",
    description: "Paper mache, paint, light fixture",
    year: "2024",
    width: 667,
    height: 1000,
  },
  {
    type: "image",
    src: "/cigarettes.jpg",
    alt: "Silver ceramic lustre ashtray full of beaded cigarettes",
    title: "BEADED CIGARETTES",
    description: "Lucite & glass beads",
    year: "2024",
    width: 1500,
    height: 1000,
  },
  {
    type: "image",
    src: "/do-not-copy.GIF",
    alt: "Ceramic nerikomi vase with DO NOT COPY inlaid repeatedly in coloured clay and brass keys dangling all around",
    title: "DO NOT COPY",
    description: "              Stoneware, mason stain, glaze & brass keys",
    year: "2025",
    width: 635,
    height: 1000,
  },
  {
    type: "image",
    src: "/do-not-copy-small.jpg",
    alt: "Ceramic nerikomi vase with DO NOT COPY inlaid repeatedly in coloured clay and brass keys dangling all around",
    title: "DO NOT COPY",
    description: "              Stoneware, mason stain, glaze & brass keys",
    year: "2025",
    height: 1000,
    width: 635,
  },
  {
    type: "image",
    src: "/slurp-full.jpg",
    alt: "Ceramic fire hydrant sculpture with streams of water",
    title: "SLURP",
    description: "Stoneware, underglaze, glaze, lucite & water",
    year: "2024",
    height: 1000,
    width: 1000,
  },
  {
    type: "image",
    src: "/slurp-close.jpg",
    alt: "Closeup of ceramic fire hydrant sculpture with streams of water and sculpted word SLURP",
    title: "SLURP",
    description: "Stoneware, underglaze, glaze, lucite & water",
    year: "2024",
    height: 1000,
    width: 1000,
  },
  {
    type: "image",
    src: "/kong-lamp.jpg",
    alt: "Multicolored marbled hanging ceramic lampshade in the shape of a dog toy",
    title: "KONG LAMP",
    description: "Stoneware, porcelain, pigment, glaze, light fixture",
    year: "2024",
    height: 1000,
    width: 1000,
  },
  {
    type: "image",
    src: "/all-dogs.jpg",
    alt: "Giant textile chain with dog tags that say ALL DOGS GO TO HEAVEN",
    title: "ALL DOGS GO TO HEAVEN",
    description: "Polyester fabric, batting, thread & acrylic beads",
    year: "2024",
    width: 1000,
    height: 1000,
  },
  {
    type: "image",
    src: "/keys.jpg",
    alt: "Carved wood and sculpted papier mache keys on a lucite chain",
    title: "KEYS PLEASE",
    description: "Carved douglas fir, papier mache, silver foil & lucite",
    year: "2024",
    width: 667,
    height: 1000,
  },
  {
    type: "image",
    src: "/bead-maze-close.jpg",
    alt: "Closeup of a bead maze sculpture with lucite, glass and ceramic beads",
    title: "BEAD MAZE - collaboration with Etty Anderson",
    description: "Wood, lucite & ceramic beads",
    year: "2024",
    height: 1000,
    width: 635,
  },
  {
    type: "image",
    src: "/receptionists-pen.jpg",
    alt: "Beaded pen on a long beaded chain",
    title: "RECEPTIONIST'S PEN",
    description: "              Glass seed beads, PVC tubing & pen",
    year: "2024",
    width: 667,
    height: 1000,
  },
  {
    type: "image",
    src: "/tall-chair.jpg",
    alt: "Comically tall lime green & clear lucite chair with speckled ceramic bag and giant ceramic cigarette butt",
    title: "HIGH CHAIR",
    description: "Wood, lucite & paint",
    year: "2024",
    width: 667,
    height: 1000,
  },
];
